on:
  push:
    branches:
      - v*
      - issue/*
name: Porsche UI Kit
jobs:
  filter:
    name: Filter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: ./images/node/
      env:
        PORSCHE_NPM_REGISTRY_TOKEN: ${{ secrets.PORSCHE_NPM_REGISTRY_TOKEN }}
      with:
        entrypoint: run-install
    - name: Build
      uses: ./images/node/
      with:
        entrypoint: run-build
    - name: Deploy
      uses: ./images/node/
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
      with:
        entrypoint: run-deploy
