on: push
name: Porsche UI Kit
jobs:
  filter:
    name: Filter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Filter
      uses: ./images/node/
      env:
        GIT_FILTER: ^refs/heads/(v[0-9]+|issue/[0-9]+)$
      with:
        entrypoint: run-filter
    - name: Install
      uses: ./images/node/
      env:
        PORSCHE_NPM_REGISTRY_TOKEN: ${{ secrets.PORSCHE_NPM_REGISTRY_TOKEN }}
      with:
        entrypoint: run-install
    - name: Build
      uses: ./images/node/
      with:
        entrypoint: run-build
    - name: Slack
      uses: ./images/node/
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        entrypoint: run-slack
    - name: Deploy
      uses: ./images/node/
      env:
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
      with:
        entrypoint: run-deploy
